spring.application.name=agroorbit-api

# Oracle DB - ajustar com suas credenciais FIAP
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM555189
spring.datasource.password=040506
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false
spring.flyway.out-of-order=true

# JWT
jwt.secret=agroorbit-secret-key-fiap-global-solution-2026
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Tomcat: permite @ e outros caracteres especiais no path
server.tomcat.relaxed-path-chars=|,{,},[,]
server.tomcat.relaxed-query-chars=|,{,},[,]

# Logs
logging.level.com.agroorbit=INFO
